---
platform: linux
image: docker:///lang/go#build
inputs:
  - name: ci
  - name: metadata
  - name: src
outputs:
  - name: compiled
run:
  path: ci/scripts/go/compile
  args:
    - src
    - compiled
    - metadata/latest-tag
