---
platform: linux
image: docker:///contains/upx
inputs:
  - name: ci
  - name: found
  - name: stripped
outputs:
  - name: packed
run:
  path: ci/scripts/go/pack
  args:
    - stripped
    - found
    - packed
