resources:
  - name: ci
    type: git
    source:
      uri: {{git-uri-pipeline-go}}
  - name: src
    type: git
    source:
      uri: {{git-uri-upstream-go}}
  - name: alpine
    type: docker-image
    source:
      repository: {{docker-image-alpine}}
  - name: go:bootstrap
    type: docker-image
    source:
      repository: {{docker-image-go}}
      tag: bootstrap
      email: {{secret-docker-email}}
      username: {{secret-docker-username}}
      password: {{secret-docker-password}}
  - name: go:build
    type: docker-image
    source:
      repository: {{docker-image-go}}
      tag: build
      email: {{secret-docker-email}}
      username: {{secret-docker-username}}
      password: {{secret-docker-password}}
  - name: go
    type: docker-image
    source:
      repository: {{docker-image-go}}
      email: {{secret-docker-email}}
      username: {{secret-docker-username}}
      password: {{secret-docker-password}}
jobs:
- name: bootstrap
  plan:
  - get: ci
    trigger: true
  - put: go:bootstrap
    params:
      build: ci/images/go/bootstrap
      cache: true
- name: build
  plan:
    - get: ci
      trigger: true
    - get: src
      trigger: true
    - get: go:bootstrap
      trigger: true
    - task: extract-metadata
      file: ci/tasks/go/extract-metadata.yaml
    - task: compile
      file: ci/tasks/go/compile.yaml
    - task: find-binaries
      file: ci/tasks/go/find-binaries.yaml
    - task: strip
      file: ci/tasks/go/strip.yaml
    - task: prepare
      file: ci/tasks/go/prepare-build.yaml
    - put: go:build
      params:
        build: prepared
        cache: true
- name: release
  plan:
    - get: ci
      trigger: true
    - get: src
    - get: go:build
      trigger: true
    - get: alpine
      trigger: true
    - task: extract-metadata
      file: ci/tasks/go/extract-metadata.yaml
    - task: compile
      file: ci/tasks/go/compile.yaml
      config:
        image: docker:///lang/go#build
    - task: find-binaries
      file: ci/tasks/go/find-binaries.yaml
    - task: strip
      file: ci/tasks/go/strip.yaml
    - task: pack
      file: ci/tasks/go/pack.yaml
    - task: prepare
      file: ci/tasks/go/prepare-release.yaml
    - put: go
      params:
        build: prepared
        cache: true
    - put: go
      params:
        build: prepared
        tag: metadata/version
