#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

test ${#} -gt 1

# The last argument given is OUT
for OUT; do OUT=${PWD}/${OUT}; done

# Each argument before the last is an IN
while test ${#} -gt 1; do
    IN=${PWD}/${1}
    cp -a ${IN} ${OUT}
    shift
done
