#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

IN=${PWD}/${1}
OUT=${PWD}/${2}
TAG_FILE=${PWD}/${3}
TAG=${TAG:-$(cat ${TAG_FILE})}

export CGO_ENABLED=0
export GOROOT_BOOTSTRAP=${GOROOT_BOOTSTRAP:-'/usr/lib/go'}
export GOROOT_FINAL=${OUT}

cd ${IN}/src
git checkout ${TAG}
./make.bash
