#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

IN=${PWD}/${1}
OUT=${PWD}/${2}

find ${IN} -type f -exec file '{}' \; | awk '/: ELF 64-bit LSB/ { print $1 }' | sed 's/:$//' | sed "s,^${IN}/,," | tee ${OUT}/binaries
cat ${OUT}/binaries | while read filename; do
    local linking_method=$(file ${IN}/${filename} | grep -Eo '\w+ linked' | awk '{print $1 }')
    echo $filename | tee -a ${OUT}/linked-${linking_method}
done
