#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

IN=${PWD}/${1}
TARGETS=${PWD}/${2}
OUT=${PWD}/${3}

cat ${TARGETS}/linked-statically | while read filename; do
    mkdir -p ${OUT}/$(dirname ${filename})
    upx --lzma -o ${OUT}/${filename} ${IN}/${filename}
done
