#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

IN=${PWD}/${1}
TARGETS=${PWD}/${2}
OUT=${PWD}/${3}

cat ${TARGETS}/binaries | while read filename; do
    mkdir -p $(dirname ${filename})
    strip -o ${OUT}/${filename} ${IN}/${filename}
done
