#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

IN=${PWD}/${1}
OUT=${PWD}/${2}

cat ${IN}/binaries | while read filename; do
    mkdir -p $(dirname ${filename})
    strip -o ${OUT}/${filename} ${IN}/${filename}
done
